Name = "dbus"
Type = "deamon"
After = ["mounts"]
ExecStart = [
    "dbus-uuidgen --ensure=/etc/machine-id",
    "install -dm755 /run/dbus",
    "dbus-daemon --system"
]
ExecStop = [
    "pkill dbus-deamon",
    "rm /run/dbus/system_bus_socket",
    "rm /etc/machind-id"
]
